version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: mygradhub-auth/Dockerfile
    container_name: mygradhub-auth
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DEVTOOLS_RESTART_ENABLED=true