spring:
  application:
    name: mygradhub-auth
  datasource:
    url: jdbc:h2:mem:mygradhubdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
jwt:
  secret-key: ${JWT_SECRET:default-secret}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
  issuer: MyGradHub

server:
  port: 8081
  error:
    include-stacktrace: never
    include-path: never

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.mygradhub: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always